version: "3.1"

services:
  map:
    image: maptiler/tileserver-gl
    restart: always
    ports:
      - 8888:8080
    volumes:
      - ./data:/data
  webapp:
    image: blackrookie/boho:v1.0
    restart: always
    volumes:
      - ./app-configuration.json:/usr/share/nginx/html/boho/assets/app-configuration.json
    ports:
      - 8081:80
