
GET https://8e03-2001-ee0-d741-1650-542d-5d86-c285-43c3.ngrok-free.app/api/rest/v1/node/e47928ba-5e5e-42ee-a546-a6a895a1ae87/device/events?dis=14&tq=week
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiYjQzMGY1NDUtOTdjMS00NGU2LTkyNjktMWRkM2M3YjczMTViIiwiZXhwIjoxNzA0NDAyNzkzfQ.Tvz4kKMVkdTJ8UscyMsMh51xwzKHzw2d0R_cgGg58Sk

###
GET https://8e03-2001-ee0-d741-1650-542d-5d86-c285-43c3.ngrok-free.app/api/rest/v1/node/08a359ec-48cd-40ae-8536-dc83b8e77a39/device/14/event/08a359ec-48cd-40ae-8536-dc83b8e77a39/image?type=full
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiYjQzMGY1NDUtOTdjMS00NGU2LTkyNjktMWRkM2M3YjczMTViIiwiZXhwIjoxNzA0NDAyNzkzfQ.Tvz4kKMVkdTJ8UscyMsMh51xwzKHzw2d0R_cgGg58Sk 

###
PATCH https://8e03-2001-ee0-d741-1650-542d-5d86-c285-43c3.ngrok-free.app/api/rest/v1/node/08a359ec-48cd-40ae-8536-dc83b8e77a39/device/14/event/08a359ec-48cd-40ae-8536-dc83b8e77a39
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiYjQzMGY1NDUtOTdjMS00NGU2LTkyNjktMWRkM2M3YjczMTViIiwiZXhwIjoxNzA0NDAyNzkzfQ.Tvz4kKMVkdTJ8UscyMsMh51xwzKHzw2d0R_cgGg58Sk 

{
  "is_verify": true
}

###
POST https://8a2f-2001-ee0-d741-1650-ec69-dbf-839d-20d7.ngrok-free.app/api/rest/v1/node/08a359ec-48cd-40ae-8536-dc83b8e77a39/device/scan_profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiYjQzMGY1NDUtOTdjMS00NGU2LTkyNjktMWRkM2M3YjczMTViIiwiZXhwIjoxNzA0NTU3OTU5fQ.rsP7MlVHYGJkXdM_XWqJe8u__tKGUFX2A2mj-jVa-Vg

{
  "ip": "192.168.100.188",
  "port": 8018,
  "user": "root",
  "password": "root"
}

###
GET https://6641-2001-ee0-d741-1470-590f-bb52-18a8-2639.ngrok-free.app/api/rest/v1/node/dca94874-0d3c-49d5-9b81-7fc48732b811/device/37/intergrate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiYjQzMGY1NDUtOTdjMS00NGU2LTkyNjktMWRkM2M3YjczMTViIiwiZXhwIjoxNzA1MzQ4NTQyfQ.O6tvq4bmfqjFNEdQDQCpCXw96v5nuhdB3cyS43o7rOs

###

POST https://6641-2001-ee0-d741-1470-590f-bb52-18a8-2639.ngrok-free.app/api/rest/v1/node/dca94874-0d3c-49d5-9b81-7fc48732b811/device/37/intergrate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiYjQzMGY1NDUtOTdjMS00NGU2LTkyNjktMWRkM2M3YjczMTViIiwiZXhwIjoxNzA1MzQ4NTQyfQ.O6tvq4bmfqjFNEdQDQCpCXw96v5nuhdB3cyS43o7rOs

{
  "rule_ids" : [13, 16],
  "milestone_id": 6,
  "guid": "",
  "service_name": "Analytic Event Milestone",
  "is_send_snapshot": true
}
###
PATCH  https://6641-2001-ee0-d741-1470-590f-bb52-18a8-2639.ngrok-free.app/api/rest/v1/node/dca94874-0d3c-49d5-9b81-7fc48732b811/device/37/intergrate/24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiYjQzMGY1NDUtOTdjMS00NGU2LTkyNjktMWRkM2M3YjczMTViIiwiZXhwIjoxNzA1MzQ4NTQyfQ.O6tvq4bmfqjFNEdQDQCpCXw96v5nuhdB3cyS43o7rOs

{
  "rule_ids" : [13],
  "milestone_id": 6,
  "guid": "abd",
  "service_name": "Analytic Event Milestone",
  "is_send_snapshot": false
}
###
DELETE   https://6641-2001-ee0-d741-1470-590f-bb52-18a8-2639.ngrok-free.app/api/rest/v1/node/dca94874-0d3c-49d5-9b81-7fc48732b811/device/37/intergrate/24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiYjQzMGY1NDUtOTdjMS00NGU2LTkyNjktMWRkM2M3YjczMTViIiwiZXhwIjoxNzA1MzQ4NTQyfQ.O6tvq4bmfqjFNEdQDQCpCXw96v5nuhdB3cyS43o7rOs