name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag blackrookie/boho:v1.0 --platform linux/amd64
    - name: Push the Docker image to registry
      run: docker push blackrookie/boho:v1.0-bh
